
<?php if($this->revision_changed) { ?>
<div class="notification" style="background: rgba(200,50,50,0.2); border: 1px solid rgba(200,50,50,0.6); color: #000; margin: 10px 0; padding: 10px; text-align: center;">
    <strong>Revision changed</strong>
</div>

<?php } ?>

<div class="property">
    <h4>Revisions</h4>

    <div class="values">
        <?php if(empty($this->revisions)) {  ?>
            <strong>No revisions to show</strong>
        <?php } else {
            foreach($this->revisions as $rev)
            { ?>
                <div>
                    <form method='post' action=''>
                        <?php echo date_format($rev['created'], 'g:ia \o\n l jS F Y');?>
                        <input type="hidden" name="revision_id" value="<?php echo $rev['id'];?>">
                        <input type="hidden" name="revision_content" value="<?php echo $rev['content'];?>">

                        <input type="submit" value="Restore">
                    </form>
                </div>
            <?php }
        } ?>
    </div>    
</div>